language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - pip install nose
  - pip install numpy
  - pip install scipy
  - pip install configparser
install:
  - python setup.py install
# command to run tests
script:
  - nosetests
