language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
before_install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - python setup.py install
# command to run tests
script:
  - nosetests
